### PR TITLE
Fix subdirectory argument scan bug

### PR DESCRIPTION
**Pull request by hmacwise**
## Context
Fix directory scan bug, overwritting the currentDir introduced a bug and broke the values file history view in the changelog.

Introduced 2 methods of populating the changelog with PR description, either using the GitHub CLI or API

## Checklist
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

### CODE REVIEW

**Comment by hmacwise** [comment]
Enriched changelog with PR description. The binary assumes the `gh` CLI tool is installed and configured, _which I think it is by default in GH runners_ (Edit - spoiler alert: **it isn't**. will need to rewrite this to use the GH api instead)

Example: 
image

**Review by mihkelparna1 — APPROVED** [review]

**Comment by hmacwise** [comment]
/wise-bot emergency-merge First PR to repo, setting up CODEOWNERS

**Comment by s0** [comment]
/wise-bot emergency-merge First PR to repo, setting up CODEOWNERS

**Pull request merged**
